// <auto-generated />
using System;
using FeatureManagement.Database.EntityFrameworkCore.Tests;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FeatureManagement.Database.EntityFrameworkCore.Tests.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20240601150921_UpdateSeedData")]
    partial class UpdateSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FeatureManagement.Database.Feature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RequirementType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e02ab394-42c6-412e-9f32-7f5d2ca8e7b6"),
                            Name = "FirstFeature",
                            RequirementType = 1
                        },
                        new
                        {
                            Id = new Guid("f5665e3e-da77-45f1-806b-6e5e9329a63f"),
                            Name = "SecondFeature",
                            RequirementType = 1
                        });
                });

            modelBuilder.Entity("FeatureManagement.Database.FeatureSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomFilterTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FilterType")
                        .HasColumnType("int");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.ToTable("FeatureSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("301f6510-3d8b-446d-8ff6-b68b2ab04ee6"),
                            FeatureId = new Guid("e02ab394-42c6-412e-9f32-7f5d2ca8e7b6"),
                            FilterType = 2,
                            Parameters = "{\"Start\": \"Mon, 01 May 2023 13:59:59 GMT\", \"End\": \"Sat, 01 July 2023 00:00:00 GMT\"}"
                        });
                });

            modelBuilder.Entity("FeatureManagement.Database.FeatureSettings", b =>
                {
                    b.HasOne("FeatureManagement.Database.Feature", "Feature")
                        .WithMany("Settings")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("FeatureManagement.Database.Feature", b =>
                {
                    b.Navigation("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
