// <auto-generated />
using System;
using FeatureManagement.Database.EntityFrameworkCore.Tests;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20250414205937_NewData")]
    partial class NewData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FeatureManagement.Database.Feature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("RequirementType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7c81e846-dc77-4aff-bf03-8dd8bb2d3194"),
                            Name = "FirstFeature",
                            RequirementType = 1
                        },
                        new
                        {
                            Id = new Guid("d3c82992-2f12-4008-9376-da37695a2747"),
                            Name = "SecondFeature",
                            RequirementType = 1
                        },
                        new
                        {
                            Id = new Guid("0ece94e6-75a0-4257-9e8e-180a297fa7d8"),
                            Name = "FeatureToUpdate",
                            RequirementType = 0
                        },
                        new
                        {
                            Id = new Guid("dd323f34-2ed5-49c1-acb7-d3b4a99bad4b"),
                            Name = "FeatureToDelete",
                            RequirementType = 1
                        });
                });

            modelBuilder.Entity("FeatureManagement.Database.FeatureSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CustomFilterTypeName")
                        .HasColumnType("longtext");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("char(36)");

                    b.Property<int>("FilterType")
                        .HasColumnType("int");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.ToTable("FeatureSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("672dc1bd-9c5b-44ce-8461-234b262a8395"),
                            FeatureId = new Guid("7c81e846-dc77-4aff-bf03-8dd8bb2d3194"),
                            FilterType = 2,
                            Parameters = "{\"Start\": \"Mon, 01 May 2023 13:59:59 GMT\", \"End\": \"Sat, 01 July 2023 00:00:00 GMT\"}"
                        },
                        new
                        {
                            Id = new Guid("8190cc07-7499-46f0-93fc-fe45bf828df3"),
                            FeatureId = new Guid("d3c82992-2f12-4008-9376-da37695a2747"),
                            FilterType = 2,
                            Parameters = "{\"Start\": \"Mon, 01 May 2023 13:59:59 GMT\", \"End\": \"Sat, 01 July 2023 00:00:00 GMT\"}"
                        });
                });

            modelBuilder.Entity("FeatureManagement.Database.FeatureSettings", b =>
                {
                    b.HasOne("FeatureManagement.Database.Feature", "Feature")
                        .WithMany("Settings")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("FeatureManagement.Database.Feature", b =>
                {
                    b.Navigation("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
