name: Build

on:
  push:
    branches: [main]
    tags: ['v*.*.*']
    paths-ignore: ['**/*.md', '**/*.png', '**/*.txt']
  pull_request:
    branches: [dev, main]
    types: [opened, reopened, synchronize, edited, ready_for_review]
    paths-ignore: ['**/*.md', '**/*.png', '**/*.txt']

env:
  CONFIGURATION: 'Release'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet_version: ['6.0.x', '8.0.x']

    steps:
      - uses: actions/setup-dotnet@v4
      - name: .NET setup
        uses: ./.github/workflows/dotnet-setup.yml
        with:
          dotnet_version: ${{ matrix.dotnet_version }}

      - name: Run build
        shell: pwsh
        run: ./build.ps1 -Configuration ${{ env.CONFIGURATION }}